---
- hosts: 172.31.18.199
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myfirsttaskresult
  
  - name: I want to display the first task result
    debug:
      msg: "{{myfirsttaskresult}}"