---

- hosts: 172.31.18.199
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: Copy static file into ansible node server.
    copy:
      src: mytestfile
      dest: /home/ubuntu/mystaticfile

  - name: Installing webserver apache2
    apt:
      name: apache2
      state: present

  - name: Copying dynamic file to node server.
    template: 
       src: myindex.j2
       dest: /var/www/html/index.html
      