---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
   - name: "i want to install apache2"
     apt:
      name: apache2
      state: absent
     when: ansible_os_family == "Debian"
   - name: start webserver on ubuntu
     service:
       name: httpd
       state: stopped
     when: ansible_os_family == "Redhat"
   - name: Install webserver on redhat ansible nodes
     yum:
       name: httpd
       state: present
     when: ansible_os_family == "RedHat"
   - name: starting service on redhat
     service:
       name: httpd
       state: started
     when: ansible_os_family == "Redhat"