---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
   - name: "i want to install apache2"
     apt:
      name: "{{mywebserverspackonubuntu}}"
      state: present
     when: ansible_os_family == "Debian"
   - name: start webserver on ubuntu
     service:
       name: "{{mywebserverspackonubuntu}}"
       state: restarted
     when: ansible_os_family == "Debian"
   - name: Install webserver on redhat ansible nodes
     yum:
       name: "{{mywebserverspackonredhat}}"
       state: present
     when: ansible_os_family == "RedHat"
   - name: starting service on redhat
     service:
       name: "{{mywebserverspackonredhat}}"
       state: started
     when: ansible_os_family == "RedHat"