---
- hosts: all
  become: yes
  tasks:
  - name: Inslling nginx webser to node server
    apt:
      name: nginx
      state: present
  - service:
      name: nginx
      state: started
  - name: Uninstalling apache2 server
    apt:
      name: apache2
      state: absent
  - service:
      name: apache2
      state: stopped