---
- hosts: all
  become: yes
  tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: absent
  - name: I want to start the webserver
    service: 
      name: apache2
      state: stopped